data:
  tokenizer: null
  train_files: Intelligent-Internet/ii-verl-example
  val_files: Intelligent-Internet/ii-verl-example
  train_split: train
  val_split: test
  prompt_key: messages
  max_prompt_length: 1024
  max_response_length: 8192
  train_batch_size: 128
  val_batch_size: 128
  filter_overlong_prompts: true

actor_rollout_ref:
  model:
    path: deepseek-ai/DeepSeek-R1-Distill-Qwen-1.5B
    enable_gradient_checkpointing: true
    use_remove_padding: true

  actor:
    strategy: fsdp
    ppo_mini_batch_size: 64
    use_dynamic_bsz: true
    ulysses_sequence_parallel_size: 1
    ppo_max_token_len_per_gpu: 32768

    use_kl_loss: True
    kl_loss_coef: 0.001
    kl_loss_type: low_var_kl
    
    optim:
      lr: 1.0e-06

  ref:
    param_offload: true
    
  rollout:
    name: vllm
    temperature: 0.6
    gpu_memory_utilization: 0.8
    tensor_model_parallel_size: 1
    n: 8
    
reward_model:
  enable: false

# Enable remote reward server
reward_api:
  enable: true
  api_url: http://localhost:8000
  max_workers: 20
  timeout: 30
  verification_info_column: verification_info
  save_dir: debug_data/
  save_freq: 1

algorithm:
  adv_estimator: grpo
  kl_penalty: kl
  kl_ctrl:
    type: fixed
    kl_coef: 0.001

trainer:
  total_epochs: 15
  project_name: ii-verl
  experiment_name: grpo
  nnodes: 1
  n_gpus_per_node: 8
  save_freq: 50
  test_freq: 50
  default_local_dir: checkpoints/grpo

# Just ignore this
# GRPO does not need critic
# We set the batch size for passing validation
critic:
  ppo_micro_batch_size_per_gpu: 1