data:
  train_files: "./data/gsm8k/train.parquet"
  val_files: "./data/gsm8k/test.parquet"
  train_batch_size: 1024
  max_prompt_length: 512
  max_response_length: 512
  filter_overlong_prompts: true
  truncation: "error"

actor_rollout_ref:
  model:
    path: deepseek-ai/deepseek-llm-7b-chat
    use_remove_padding: true
    enable_gradient_checkpointing: true
  actor:
    optim:
      lr: 1e-6
    ppo_mini_batch_size: 256
    ppo_micro_batch_size_per_gpu: 16
    fsdp_config:
      param_offload: false
      optimizer_offload: false
  rollout:
    log_prob_micro_batch_size_per_gpu: 32
    tensor_model_parallel_size: 4
    name: vllm
    gpu_memory_utilization: 0.4
  ref:
    log_prob_micro_batch_size_per_gpu: 32
    fsdp_config:
      param_offload: true

critic:
  optim:
    lr: 1e-5
  model:
    use_remove_padding: true
    path: deepseek-ai/deepseek-llm-7b-chat
    enable_gradient_checkpointing: true
    fsdp_config:
      param_offload: false
      optimizer_offload: false
  ppo_micro_batch_size_per_gpu: 32

algorithm:
  kl_ctrl:
    kl_coef: 0.001

trainer:
  critic_warmup: 0
  project_name: "verl_example_gsm8k"
  experiment_name: "deepseek_llm_7b_function_rm"
  n_gpus_per_node: 8
  nnodes: 1
  save_freq: -1
  test_freq: 1
  total_epochs: 15
